### PR TITLE
Feature/taxonomy mapper

### PR DESCRIPTION
**Pull request by sebastiansibelle**
Added a new Mapping helper to map taxonomy ids to titles.

### CODE REVIEW

**Comment by andrewmclagan** [comment]
Cool

**Comment by andrewmclagan** [comment]
Let me take a look

**Comment by andrewmclagan** [comment]
Okay @sebastiansibelle there are pretty significant changes to this PR.

### Solution:

I realised while reading the PR that what we are doing is essentially built into the `ResponseSelector` feature that I recently added to this package. 

I pointed you in the direction of the Mapper pattern although really that was incorrect as we are not mapping we are selecting. Mapping - maps one data structure to another - as we do in `api-autopost` we map their job format to our job format. A lookup by Id in a hash-table (dictionary) is the selector pattern e.g. can be *memoized*.

1. I simply wrote a function on `ResponseSelector::taxonomyTermById(string $taxonomy, int $id)` that does a lookup on our api response.

2. Then I wrote a `TaxonomyResource` class with a `TaxonomyResource::getTermById(string $taxonomy, int $id)` function that internally calls `api->appData()` then selects from the response using `ResponseSelector`.

That way we can use the following sugar syntax to get what we want:

```php

// Facade accessor method

$term = EthicalJobs::resource('taxonomies')->getTermById('locations', 9);

echo $term->title;

// OR using the resource as properties approach

function(ApiClient $api) {
    $term = $api->taxonomies->getTermById('locations', 9);
    return $term->title;
}

```

------

### Issues:

1. My issue with having a direct route to grab the title in the SDK is that approach is really specific and the SDK is a general utility. The title selection should be the domain of `api-alerts` as *it* wants the title. A term selection process is more re-usable and agnostic.

2. In your `MapperInterface` the function definition for `map()` makes the interface pointless. Your parameters are named `int $taxonomyId, string $type` this is specific to the `TaxonomyMapper` implementation of the interface. Another Mapper implementation using the `MapperInterface` should not have to be tied to the idea of a `$taxonomyId` as it could be mapping anything, perhaps a `JobSeekerUser` to a `EmployerUser`. Looking at this class interface was what actually triggered me to think *"ah we got the architecture wrong, we are not mapping we are selecting..."* Remeber the point of an interface is to enforce a contract so a dev knows what to expect. If you cant figure out the params for an interface its usually a code smell that the approach is wrong.

3. In the `TaxonomyMapper` there is a function `fetchTaxonomyDictionary()` that returns a collection. Although the usage of this function within the public `map()` function never utilises any `Collection` specific functionality - simply array access and thus is extra overhead and surface area for bugs.

4. The DocBloc of the implementation `TaxonomyMapper` of the `MapperInterface` is repeated. Usually you should use the:

```php
    /**
     * {@inheritdoc}
     */ 
```

within an implementation so that API doc generators can follow this through. We are very close to perhaps using an API doc generator attached to docs.ethicalops.com.au as Laravel docs do.

**Comment by andrewmclagan** [comment]
If this approach is accepted we need to:

* Remove the `Mappers` dir, code and tests.
* Refactor the related PR on `api-alerts/feature/make-alerts-api-interface-blind-of-search-props` as I changed the name of some functions in `ResponseSelector` to have a more consistent approach.
* Refactor the same branch to deal with a `$term->title` and not a direct `$title`.
* Tag as `x.X.x`  version as I dont think that anything is using the new `ResponseSelector` yet thus we can get away without a BC.

Changes to selector api:

`entityByResult()`
`entityById()`
`taxonomyTermById()`
`entities()`

**Comment by sebastiansibelle** [comment]
Yep makes sense! Do you want to do that work on api-alerts or me?

**Pull request merged**
